### ISSUE TITLE
mitm.it

### ISSUE THREAD

**Issue by fopina** [mhils/HoneyProxy#83]
Not something really important but mitmproxy mitm.it webapp is great to make it easy to install the certificates.

Can't it be used in honeyproxy as well?

**Comment by mhils** [comment]
Thanks for the suggestion. We're working on mitmweb for mitmproxy as the successor of HoneyProxy, which already has a "Install certificate" button which leads to mitm.it.

Cheers,
Max

**Comment by fopina** [comment]
Nice to hear, is it this https://github.com/mitmproxy/mitmproxy/tree/integrate_honeyproxy (so I can track it)?

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/tree/master/web - there's already an undocumented `mitmweb` executable that ship with mitmproxy as well.
